version: "3"
services:
    api:
        container_name: apiApp
        build:
            context: .
        volumes:
            - /var/www/apps/api:/app
        ports:
            - 8086:8086
        environment:
            - NODE_ENV=development
            - ES_HOST=elastic
            - ELASTIC_URL=http://elastic:9200
        links:
            - elastic
        depends_on:
            - elastic
        networks: 
            - esnet

    elastic:
        container_name: elasticApi
        image: elasticsearch:8.1.2
        volumes:
            - /var/www/elastic:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node    
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
        ports:
            - 9200:9200
            - 9300:9300
        networks: 
            - esnet
           
networks:
    esnet: